name: DevOps Activity Bot

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.name "devops-bot"
          git config --global user.email "bot@github.com"

      - name: Run bot
        run: python auto_commit.py

      - name: Push
        run: git push
